"""Cluster-aware 80/10/10 splits.

Reads ``ml/data/clusters/clusters.csv`` and assigns WHOLE CLUSTERS (not
individual sequences) to train/val/test. This is the property that
keeps a sequence and its 40%-identity neighbour from landing in
different splits — which is what would otherwise inflate held-out AUC
by 10-15 points on AMP data.

Strategy:
  - Group clusters by class composition: amp-pure, neg-pure, or mixed.
  - Per class, sort clusters by size descending and assign each to the
    split with the largest remaining capacity (greedy bin-packing).
  - Mixed clusters (an AMP and a non-AMP within 40% identity) go to
    train — they're noisy enough that we don't want them in val/test.

Seed=42 throughout, deterministic. Writes:

  ml/data/splits/train.csv    sequence_id, cluster_id, is_amp
  ml/data/splits/val.csv      "
  ml/data/splits/test.csv     "
  ml/data/splits/SPLIT_NOTES.md   methodology + final counts

Acceptance per HANDOFF.md section 6:
  - Split files exist
  - tests/test_splits.py passes (no cluster spans splits)
  - Per-class split sizes within +/- 5% of 80/10/10
"""
from __future__ import annotations

import csv
import sys
from collections import Counter, defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CLUSTERS_DIR = PROJECT_ROOT / "ml" / "data" / "clusters"
SPLITS_DIR = PROJECT_ROOT / "ml" / "data" / "splits"
CLUSTERS_CSV = CLUSTERS_DIR / "clusters.csv"
TRAIN_CSV = SPLITS_DIR / "train.csv"
VAL_CSV = SPLITS_DIR / "val.csv"
TEST_CSV = SPLITS_DIR / "test.csv"
NOTES = SPLITS_DIR / "SPLIT_NOTES.md"

SEED = 42
TARGET_FRACTIONS = {"train": 0.80, "val": 0.10, "test": 0.10}


def load_clusters():
    rows = []
    with CLUSTERS_CSV.open("r", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for r in reader:
            r["cluster_id"] = int(r["cluster_id"])
            r["is_amp"] = int(r["is_amp"])
            rows.append(r)
    return rows


def group_clusters(rows):
    """Return (cluster_to_members, cluster_class) dicts.

    cluster_class[cid] is "amp" if all members are positives, "neg" if all
    are negatives, "mixed" otherwise.
    """
    cluster_to_members = defaultdict(list)
    for r in rows:
        cluster_to_members[r["cluster_id"]].append(r)
    cluster_class = {}
    for cid, members in cluster_to_members.items():
        classes = {m["is_amp"] for m in members}
        if classes == {1}:
            cluster_class[cid] = "amp"
        elif classes == {0}:
            cluster_class[cid] = "neg"
        else:
            cluster_class[cid] = "mixed"
    return cluster_to_members, cluster_class


def assign_splits(cluster_to_members, cluster_class):
    """Greedy bin-packing per class. Mixed clusters go to train."""
    assignment = {}
    by_class = defaultdict(list)
    for cid, members in cluster_to_members.items():
        by_class[cluster_class[cid]].append((cid, len(members)))

    for class_name in ("amp", "neg"):
        clusters = sorted(by_class[class_name], key=lambda x: (-x[1], x[0]))
        total = sum(size for _, size in clusters)
        targets = {name: total * frac for name, frac in TARGET_FRACTIONS.items()}
        current = {"train": 0, "val": 0, "test": 0}
        for cid, size in clusters:
            deficits = {name: targets[name] - current[name] for name in current}
            chosen = max(deficits, key=lambda k: deficits[k])
            assignment[cid] = chosen
            current[chosen] += size

    for cid, _ in by_class.get("mixed", []):
        assignment[cid] = "train"

    return assignment


def write_split_csv(path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["sequence_id", "cluster_id", "is_amp"])
        for r in rows:
            writer.writerow([r["sequence_id"], r["cluster_id"], r["is_amp"]])


def summarize(split_rows):
    """Return per-split (n, n_amp, n_neg) tuples for the notes file."""
    out = {}
    for name, rows in split_rows.items():
        n = len(rows)
        amp = sum(1 for r in rows if r["is_amp"] == 1)
        neg = n - amp
        out[name] = (n, amp, neg)
    return out


def write_notes(summary, n_clusters, class_counts):
    NOTES.parent.mkdir(parents=True, exist_ok=True)
    total = sum(n for n, _, _ in summary.values())
    lines = [
        "# Split notes",
        "",
        "*Auto-generated by `ml/scripts/make_splits.py`. Re-run with `dev.bat splits`.*",
        "",
        "## Method",
        "",
        "Cluster-aware 80/10/10 split. Whole mmseqs2 clusters at 40% identity "
        "are assigned to a single split via greedy bin-packing (largest cluster "
        "first, placed in the split with the largest remaining capacity). "
        "Class-pure clusters bin-pack independently per class so positives and "
        "negatives both hit the 80/10/10 target; mixed clusters (an AMP within "
        "40% identity of a non-AMP) go to train so the held-out splits stay "
        "label-clean. Seed=42, deterministic.",
        "",
        f"Source: `{CLUSTERS_CSV.relative_to(PROJECT_ROOT)}` ({n_clusters} clusters).",
        "",
        f"Cluster class composition: amp-pure={class_counts['amp']}, "
        f"neg-pure={class_counts['neg']}, mixed={class_counts['mixed']}",
        "",
        "## Final counts",
        "",
        "| Split | N | positives | negatives | pos fraction |",
        "|---|---|---|---|---|",
    ]
    for name in ("train", "val", "test"):
        n, amp, neg = summary[name]
        frac = (n / total) if total else 0.0
        pos_frac = (amp / n) if n else 0.0
        lines.append(f"| {name} | {n:,} ({frac:.1%}) | {amp:,} | {neg:,} | {pos_frac:.1%} |")
    lines.append("")
    NOTES.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[splits] wrote {NOTES}")


def main():
    if not CLUSTERS_CSV.exists():
        print(f"[splits] {CLUSTERS_CSV} not found. Run dev.bat cluster first.")
        return 1
    rows = load_clusters()
    cluster_to_members, cluster_class = group_clusters(rows)
    class_counts = Counter(cluster_class.values())
    print(f"[splits] {len(cluster_to_members)} clusters: "
          f"amp-pure={class_counts['amp']}, neg-pure={class_counts['neg']}, "
          f"mixed={class_counts['mixed']}")

    assignment = assign_splits(cluster_to_members, cluster_class)

    split_rows = {"train": [], "val": [], "test": []}
    for r in rows:
        split_rows[assignment[r["cluster_id"]]].append(r)
    for name, sorted_key in (("train", TRAIN_CSV), ("val", VAL_CSV), ("test", TEST_CSV)):
        split_rows[name].sort(key=lambda r: r["sequence_id"])
        write_split_csv(sorted_key, split_rows[name])
        print(f"[splits] wrote {sorted_key.name}: {len(split_rows[name])} sequences")

    summary = summarize(split_rows)
    total = sum(n for n, _, _ in summary.values())
    for name in ("train", "val", "test"):
        n, amp, neg = summary[name]
        frac = n / total
        target = TARGET_FRACTIONS[name]
        delta_pct = (frac - target) * 100
        print(f"[splits] {name}: {n:,} sequences "
              f"({frac:.1%}, target {target:.0%}, delta {delta_pct:+.2f}pp) "
              f"amp={amp:,} neg={neg:,}")

    write_notes(summary, len(cluster_to_members), class_counts)
    return 0


if __name__ == "__main__":
    sys.exit(main())
